
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 08 18:17:06 COT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Select = 7;
  public static final int Insert = 8;
  public static final int From = 4;
  public static final int Revoke = 2;
  public static final int Punto = 14;
  public static final int ERROR = 15;
  public static final int EOF = 0;
  public static final int T_On = 3;
  public static final int P_coma = 5;
  public static final int Coma = 6;
  public static final int Update = 9;
  public static final int Identificador = 13;
  public static final int error = 1;
  public static final int All = 11;
  public static final int ReservadaG = 12;
  public static final int Delete = 10;
}

